### ISSUE TITLE
Limitations of Review.created Field

### ISSUE THREAD

**Issue by nuthanmunaiah** [andymeneely/sira-nlp#1]
# Description

The current model specification for the table containing code reviews has the `created` field as an instance of `DateTimeField`. The `DateTimeField` supports automatic unpacking of individual date/time components (such as year, month, day, hour, minutes, and seconds) using the `created__component` construct. The automatic unpacking enables filtering reviews by components of `created`. However, if one wishes to get a list of all years for which the database has reviews for, the `DateTimeField` does not allow for it.

# Enhancement

Proposed enhancement is to add a new field, `year`, of type `PositiveSmallIntegerField` to the model specification to contain the year in which a code review was created.

**Comment by meyersbs** [comment]
I think this enhancement is no longer necessary. What do you think, @nuthanmunaiah?

**Comment by nuthanmunaiah** [comment]
Agreed. I haven't come across a situation that warrants this enhancement.
