### ISSUE TITLE
Very Slow TF-IDF Calculation

### ISSUE THREAD

**Issue by meyersbs** [andymeneely/sira-nlp#10]
## Problem

Calculation of TF-IDF for a large corpus takes quite a while. I ran the process for about an hour and only got 25 or so TF-IDF scores -- this is unacceptable.

I have traced the issue to calculating the number of documents that contain the given term. See `/app/queryStrings.py` function `queryDocumentFrequency(...)`.

## Solution

Recall that Document Frequency (DF) = Number of Documents Containing Term / Total Number of Documents. If we could add a column to the Token table, perhaps called `rev_frequency`, and save the number of reviews containing the token in that row, we could directly query for that column very quickly. The downfall of this approach is the initial time needed to populate this new column. Another issue is that this would limit us to calculating TF-IDF by token; if we wanted to calculate TF-IDF by lemma, we would need another new column to store the number of reviews containing that lemma.

## Help Wanted

The solution I proposed doesn't seem feasible, but I could be wrong. Can you make any suggestions? Or perhaps my query in the function referenced above is inefficient and can be sped up?

**Comment by nuthanmunaiah** [comment]
The problem is not just the time, I also noticed that the memory usage was at its peak during a run of the `tfidf` command earlier this evening. I'll review the queries in `queryStrings.py` file and suggest optimizations, if any.

**Comment by andymeneely** [comment]
Do we have the proper indices on the table? Lookup by lemma, that is.

**Comment by nuthanmunaiah** [comment]
Yes, I have indexed both the `text` and `base` columns of the `token` table. Here's are the index definitions as reported by PostgreSQL:

```
insights=# \d token
...
   "token_base_f2977e29_like" btree (base text_pattern_ops)
   "token_text_637bfb24_like" btree (text text_pattern_ops)
```

**Comment by meyersbs** [comment]
I have made a number of changes to the tfidf command flow in my local branch. If you have any suggestions/updates, let me know and I can implement them prior to pushing my changes.

**Comment by meyersbs** [comment]
## Updates

I just ran another test. TF-IDF was calculated for 112 reviews in an hour. This is a 450% increase from my previous implementation (25 reviews/hour). However, it's still slow. Perhaps Nuthan can walk me through parallelizing the calculations?

**Comment by meyersbs** [comment]
We created materialized views to simplify the TF-IDF calculation process by reducing the number of `JOINS` we needed to do.
