### ISSUE TITLE
Incorrect Token Frequency

### ISSUE THREAD

**Issue by nuthanmunaiah** [andymeneely/sira-nlp#14]
# Description

The `Summarizer` class in `app/lib/nlp/summarizer.py` is a utility class that produces a summary (token, lemma, frequency, pos) of all tokens in a block of text. The approach to compute token frequency, however, is flawed.

# Problem

The part-of-speech of the token is not taken into consideration when counting. For example, the summarization of `+ dgozman@chromium.org, pkasting@google.com` produces `('@', '@', 2, 'NNP')` and `('@', '@', 2, 'CD')` incorrectly suggesting that there are four instances of `@` in the text.

# Proposed Solution

The proposed solution is to consider the part-of-speech of the token when counting. The call to `counter.Counter()` in the `execute` method of `app.lib.nlp.summarizer.Summarizer` would take a list of `(token, pos)` rather than a list of `token`.

**Comment by meyersbs** [comment]
OH. That's bad. Good catch!

**Comment by meyersbs** [comment]
Resolved in commit [68fb9af](https://github.com/andymeneely/sira-nlp/commit/68fb9af3c53d5176d4c79062a5d256048b9032b4).
