### ISSUE TITLE
Discrepancy in Sentence Splitting

### ISSUE THREAD

**Issue by nuthanmunaiah** [andymeneely/sira-nlp#16]
# Description

When loading code reviews to the database we split code review messages into sentences. The sentences are then analyzed individually to collect the various metrics being studies in the research project. One of the metrics---sentiment of the text in the sentence---is collected using Stanford CoreNLP. Stanford CoreNLP's text annotation pipeline also splits the text into sentences before annotating each sentence with sentiment evaluation.

# Problem

The outcome of sentiment analysis is being stored in the database as a JSON object of the form `{"neg": n, "pos": n, "neut": n, "vneg": n, "vpos": n}` where n is the number of sentences that were categorized as one of the five sentiment classes. Since the input to the Stanford CoreNLP suite is now a sentence, the value of `n` can, in theory, be either 0 or 1 and at most one `n` can be 1. However, there are 81,343 instances in the database that violate this theory suggesting that CoreNLP is further splitting sentence into component sentences.

**Comment by meyersbs** [comment]
## Example

| ID     | text                                                                                 | neg | pos | neut | vneg | vpos |
|:------:|:-------------------------------------------------------------------------------------|:---:|:---:|:----:|:----:|:----:|
| 736585 | I.e., chromiumos_image.bin, chromiumos_image_base.bin, chromium_image_test.bin, etc. | 0   | 2   | 2    | 0    | 0    |

| sentiment | CoreNLP sentence            |
|:----------|:----------------------------|
| neut      | I.e., chromiumos_image.     |
| pos       | bin, chromiumos_image_base. |
| pos       | bin, chromium_image_test.   |
| neut      | bin, etc.                   |

In this example, we can clearly see that CoreNLP is further splitting sentence `736585` into four sentences. The split occurs when CoreNLP sees a file extension.

## Solution

In `/app/lib/nlp/analyzers/sentiment.py` change the `PARAMS` variable to: `{'properties': "{'annotators': 'sentiment', 'ssplit.isOneSentence': 'true'}"}`. This will tell CoreNLP not to split the input. I have tested this and it works. ([source](https://stanfordnlp.github.io/CoreNLP/ssplit.html))

<b>Note:</b> This issue reinforces the need for us to replace source code snippets with `<<CODE>>` and ignore tokens with the `token` field `<<CODE>>` when we aggregate our analyses. (Described in #7)

**Comment by nuthanmunaiah** [comment]
I would imagine this to impact the sentence parses we have in the database since we don't set the `ssplit.isOneSentence` property when loading the sentence parses.

**Comment by meyersbs** [comment]
Implemented same fix for sentence parsing: [85dd101](https://github.com/andymeneely/sira-nlp/commit/85dd1010466240db38697db99f4b2c74b2e2198b)
