### ISSUE TITLE
Database Index

### ISSUE THREAD

**Issue by nuthanmunaiah** [andymeneely/sira-nlp#2]
# Description

The approach to identifying all code reviews that include a particular file requires the `review.document` column (which is of type `jsonb`) to be indexed for improved query performance. `json` and `jsonb` typed columns in PostgreSQL are typically indexed using the Generalized Inverted Index (GIN) in PostgreSQL. PostgreSQL supports two different operator classes for GIN indexes: `jsonb_ops` and `jsonb_path_ops`. For more information on the differences between these two operator classes, refer to the PostgreSQL article on [`jsonb` Indexing](https://www.postgresql.org/docs/9.5/static/datatype-json.html#JSON-INDEXING).

# Limitation

The GIN index only improves the performance of queries that operate at the top-level of the JSON document. The limitation may be overcome using the [indexes on expressions](https://www.postgresql.org/docs/8.1/static/indexes-expressional.html) feature of PostgreSQL. However, the structure of the JSON document stored in the `review.document` column prevents the creation of an index based on expressions.

## Example

The structure of the JSON document stored in `review.document` column follows a pattern shown below.

```json
{
    "issue": 1,
    "patchsets": {
        "1": {
            "files": {
                "path/to/foo.c": {"id": 10001},
                "path/to/bar.c": {"id": 10002}
            }
        },
        "2": {
            "files": {
                "path/to/foo.c": {"id": 20001},
                "path/to/bar.c": {"id": 20002},
                "path/to/baz.c": {"id": 20003},
            }
        }
    }
}
```

The query to identify all code reviews that include the file `path/to/baz.c` is shown below.

```postgresql
SELECT interim.id
FROM (
    SELECT r.id, jsonb_object_keys(value #> '{"files"}') AS file
    FROM review r, jsonb_each(jsonb_extract_path(r.document, 'patchsets'))
) interim
WHERE interim.file LIKE 'path/to/baz.c';
```

The output from `EXPLAIN ANALYZE` (included below) for this query before and after adding the index to the `review.document` column shows no marked difference.

**Before Creation of Index**

```postgresql-console
                                                           QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------
 Subquery Scan on interim  (cost=0.01..139615762.38 rows=39421850 width=8) (actual time=96558.512..96558.512 rows=0 loops=1)
   Filter: (interim.file ~~ 'path/to/baz.c'::text)
   Rows Removed by Filter: 19340296
   ->  Nested Loop  (cost=0.01..41061137.38 rows=7884370000 width=40) (actual time=0.068..93260.736 rows=19340296 loops=1)
         ->  Seq Scan on review r  (cost=0.00..62413.37 rows=788437 width=469) (actual time=0.034..427.952 rows=788437 loops=1)
         ->  Function Scan on jsonb_each  (cost=0.01..1.00 rows=100 width=32) (actual time=0.105..0.106 rows=2 loops=788437)
 Planning time: 0.155 ms
 Execution time: 96558.545 ms
(8 rows)
```

**After Creation of Index**

```postgresql-console
                                                           QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------
 Subquery Scan on interim  (cost=0.01..139615762.38 rows=39421850 width=8) (actual time=105267.175..105267.175 rows=0 loops=1)
   Filter: (interim.file ~~ 'path/to/baz.c'::text)
   Rows Removed by Filter: 19340296
   ->  Nested Loop  (cost=0.01..41061137.38 rows=7884370000 width=40) (actual time=0.130..101909.068 rows=19340296 loops=1)
         ->  Seq Scan on review r  (cost=0.00..62413.37 rows=788437 width=469) (actual time=0.018..439.074 rows=788437 loops=1)
         ->  Function Scan on jsonb_each  (cost=0.01..1.00 rows=100 width=32) (actual time=0.116..0.116 rows=2 loops=788437)
 Planning time: 1.606 ms
 Execution time: 105267.305 ms
(8 rows)
```

# Solution

The design decision to overcome the limitations of the GIN index is to introduce a new field to the JSON document stored in the `review.document` column. The new field, named `files`, will be an array of strings containing a union of all the file names from all the patchsets in the code review. The new field enables the creation of a GIN index based on the expression `document -> 'files'`.

The introduction of the `files` field simplifies the query while improving its performance. The query and the output from the `EXPLAIN ANALYZE` of the query are shown below:

```postgresql
SELECT r.id
FROM review r
WHERE r.document -> 'files' @> '["path/to/baz.c"]';
```

```postgresql-console
                                                               QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on review r  (cost=16.98..460.24 rows=126 width=8) (actual time=0.025..0.025 rows=0 loops=1)
   Recheck Cond: ((document -> 'files'::text) @> '["path/to/baz.c"]'::jsonb)
   ->  Bitmap Index Scan on idxgin_review_document_files  (cost=0.00..16.95 rows=126 width=0) (actual time=0.021..0.021 rows=0 loops=1)
         Index Cond: ((document -> 'files'::text) @> '["path/to/baz.c"]'::jsonb)
 Planning time: 0.165 ms
 Execution time: 0.070 ms
(6 rows)

**Comment by andymeneely** [comment]
Hm. So there really is no way to make use of GIN without doing this? I imagine this could turn into basically schema-building for every single question we have - which was not what we wanted.

**Comment by nuthanmunaiah** [comment]
The limitation is in the way the `patchsets` field is structured in the code review JSON. For instance, if each code review had a single patchset, the keys in the `patchsets` field would have been static. We could have then used the path traversal operator (`#>`) and the key exists operator (`?`) to search for files in a code review using the query shown below:

```postgresql
SELECT r.id
FROM review r
WHERE (r.document #> '{patchsets,1,files}') ? 'path/to/baz.c';
```

Since the keys in the `patchsets` field are dynamic, we cannot use the path traversal operator. The alternative is to use an inner query but the inner query approach does not use the index leading to abysmal performance.

**Comment by meyersbs** [comment]
Moved to the [wiki](https://github.com/andymeneely/sira-nlp/wiki/Design-Decisions).
