### ISSUE TITLE
Manual Addition of Certain Missing Bugs

### ISSUE THREAD

**Issue by nuthanmunaiah** [andymeneely/sira-nlp#5]
# Description

One of the key pieces of information in the project is the mapping between vulnerabilities (identified by their CVE) and bugs. The most accurate source from which to identify the mapping is the Google's issue tracking system, Monorail. Unfortunately, the vulnerability information in Monorail is not exhaustive. To overcome this limitation, a decision was made to identify bug-vulnerability mapping from other sources such as the [Chrome Releases Blog](https://chromereleases.googleblog.com/), through the list of references on the [CVE directory](http://cve.mitre.org/), or any other online source. The files `app/data/vulnerabilities/blog.csv` and `app/data/vulnerabilities/manual.csv` contain the mappings identified from the Chrome Releases Blog and other online sources (including the CVE directory), respectively.

# Limitation

The limitation, however, is that some of the bugs contained in `blog.csv` and `manual.csv` files are publicly inaccessible due to security reasons. Consequently, a mapping between a vulnerability and a bug in the `vulnerability` database table cannot be created due to missing primary key in the `bug` table.

**Note**: Please read the Wiki on database for information on the structure of the database.

# Solution

The solution, rather a workaround, to the limitation is to manually add the missing bugs to the `bug` table to allow creation of the mapping between vulnerabilities and bugs. The manually added bug will have the following values for its fields:

 * `bug.id`: The identifier from the `blog.csv` or `manual.csv` file.
 * `bug.status`: `Redacted`, to help separate the manually added bugs.
 * `bug.type`: `Bug-Security`, to follow existing conventions.
 * `bug.document` = `{}`, an empty dictionary in Python cast to JSON.

**Comment by meyersbs** [comment]
Moved to the [wiki](https://github.com/andymeneely/sira-nlp/wiki/Design-Decisions).
