### ISSUE TITLE
Parsing Bug Identifiers from Code Review Description

### ISSUE THREAD

**Issue by nuthanmunaiah** [andymeneely/sira-nlp#6]
# Description

The mapping between a code review and bug is achieved by parsing the description of a code review to identify bug identifiers. The current implementation relies on a carefully crafted regular expression to search for bug identifiers in code review description.

# Limitation

The limitation with the current approach is that the achieving a high recall with the regular expression is close to impossible given the variation in the way bug identifiers are mentioned in the code review description. To better illustrate the limitation, examples of the line from code review description that specifies the bug identifiers is shown below.

| Code Review | Pattern |
| ----------: | ------- |
|  1996853002 | `BUG=589630^r\n` |
|  2007503002 | `BUG= 586985, 613948` |
|  2366383003 | `BUG= 411566` |
|  2002173002 | `BUG=614060` |
|  1985283003 | `BUG=612140,581716,602701` |
|  2016963002 | `BUG=604427, 609013, 612397` |
|  2016723002 | `BUG=470662, 614968, 614952\r\n` |
|  2009113002 | `BUG=364417, 366042, 364391, 403987, 403363, 405125, 417752, 459576, 482050, 564571, 571534, 588598, 596002` |
|  2000203002 | `BUG=chromium:613567` |
|  2366673004 | `BUG=chromium:639321,459361` |
|  2364873003 | `BUG=chromium:648031,chromium:648135,648063,607283,645532,chromium:648074` |
|  2369343002 | `BUG=chromium:575167, chromium:650655` |
|  2021143003 | `BUG=chromium:609831,chromium:613947,v8:5049` |
|  2357663002 | `BUG=chromium:644033,chromium:637050,648462,chromium:647807` |
|  2364873003 | `BUG=chromium:648031,chromium:648135,648063,607283,645532,chromium:648074` |
|  2021043002 | `BUG=chromium:613321, webrtc:5608"` |
|  1138343003 | `BUG=478714.` |
|   552593002 | `BUG= https://code.google.com/p/chromium/issues/detail?id=397177` |
|  2022553003 | `BUG=b/27827591, 549781` |
|  2362393002 | `BUG=649539,649291,574611,649579,v8:5378,https://github.com/dart-lang/sdk/issues/27412,chromium:638366` |
|  2264463003 | `BUG=webrtc:5949,622062,544330,638343,629679,620494,607344,637561,https://github.com/dart-lang/sdk/issues/27005,637037,611020,604452,chromium:628770,635421,605572,None,chromium:448050,626364,598405,none,629863,635877,623207,638295` |

# Solution

The proposed solution is to use to simple regular expression that can identify the line containing the bug identifiers, split by comma, and have Python independently parse each piece of text for bug identifier while accounting for any peculiarity in the way the identifier is specified.

For example, in the pattern `BUG=12345,chromium:123456,webrtc:1234567,https://code.google.com/p/chromium/issues/detail?id=12345678 `, we can consider `12345`, `chromium:123456` (after removal of `chromium:`), and `https://code.google.com/p/chromium/issues/detail?id=12345678` (after removal of `https://code.google.com/p/chromium/issues/detail?id=`), while ignoring `webrtc:1234567`. However, achieving a similar result with regular expression may be challenging.

**Comment by meyersbs** [comment]
It looks like bugs are always identified by `^BUG=$`, which makes our lives a bit simpler. Something like this should do the trick:

``` python
    bugIds = []
    bugLines = re.findall(r'^BUG=', messageText)
    for line in bugLines:
        # Remove any bugIds starting with 'webrtc'
        line = re.sub(r'webrtc:\d+,', ',', line)
        # Remove everything that isn't a number or a comma
        line = re.sub(r'[^\d,]*', '', line)
        for id in line.split(','):
            # If the id is not empty and contains only numbers
            if re.search(r'\D', id) is None and id != '':
                bugIds.append(id)
```

**Comment by meyersbs** [comment]
I found another type of bug reference in the code reviews. Instead of referencing the bug by `^BUG=`, the bug is referenced within the natural language.

```
    # message.id = 4755180
    http://b/1084719
```

It's worth noting that this is a reference to a bug, not necessarily a reference to a **related** bug. I'm not sure what we should do with this.

**Comment by nuthanmunaiah** [comment]
The bug identifier in the pattern `http://b/\d+` appears to be an identifier in an internal bug tracking system. I am inferring this from the pattern `BUG=internal b/28110563` in https://codereview.chromium.org/2054533002 and similar ones I have seen in the past.

**Comment by nuthanmunaiah** [comment]
The naive approach to parsing bug identifiers from code review descriptions improved the recall of bugs. Earlier, the `review_bug` table had 317,663 rows and with this change, the `review_bug` table has 329,926 rows (an increase of 12,263 rows).
